package typesdemo

// Enum = Scala 3's built-in way to model a fixed, closed set of values.
// Each case can carry its own parameters, replacing the old sealed-trait + case-object pattern.
enum VehicleType(val wheels: Int):
  case CarType extends VehicleType(4)
  case BikeType extends VehicleType(2)
  case TruckType extends VehicleType(6)

  def description: String = s"$this has $wheels wheels"

@main def runVehicleTypeDemo(): Unit =
  VehicleType.values.foreach(t => println(t.description)) // .values is auto-generated by enum
